require:
- 'rubocop-md'
AllCops:
  Exclude:
    - 'bin/**/*'
    - 'tmp/**/*'
    - 'docs/web/**/*'
    - 'vendor/**/*'
    - 'gemfiles/vendor/**/*'
    - 'clowne.gemspec'
  DisplayCopNames: true
  StyleGuideCopsOnly: false
  TargetRubyVersion: 2.3

Markdown:
  WarnInvalid: true

Naming/AccessorMethodName:
  Enabled: false

Naming/ClassAndModuleCamelCase:
  Exclude:
    - 'spec/**/*.rb'

Naming/UncommunicativeMethodParamName:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false

Metrics/LineLength:
  Max: 100

Style/Documentation:
  Exclude:
    - 'spec/**/*.rb'
    - 'README.md'

Style/SymbolArray:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - 'spec/**/*.rb'
    - 'Gemfile'
    - 'Rakefile'
    - '*.gemspec'
    - 'CHANGELOG.md'
    - 'README.md'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Bundler/OrderedGems:
  Enabled: false

Gemspec/OrderedDependencies:
  Enabled: false

Lint/Void:
  Exclude:
    - 'README.md'
